apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis-deployment
    app: voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: redis-pod
      app: voting-app
  template:
    metadata:
      labels:
        name: redis-pod
        app: voting-app
    spec:
      automountServiceAccountToken: false
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
