apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deployment
  labels:
    name: result-app-deployment
    app: voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: result-app-pod
      app: result-app
  template:
    metadata:
      labels:
        name: result-app-pod
        app: result-app
    spec:
      automountServiceAccountToken: false
      containers:
        - name: result-app-container
          image: vvd0502/votingapp_result:0.2
          ports:
            - containerPort: 80
