apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    name: worker-app-deployment
    app: voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: worker-app-pod
      app: worker-app
  template:
    metadata:
      labels:
        name: worker-app-pod
        app: worker-app
    spec:
      containers:
        - name: worker-app-container
          image: vvd0502/votingapp_worker:0.2
